// <auto-generated />
namespace TaskTracker.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addedmodifieddate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedmodifieddate));
        
        string IMigrationMetadata.Id
        {
            get { return "201407272046056_added modified date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
